### ISSUE TITLE
Docker Container not starting anymore

### ISSUE THREAD

**Issue by daniel156161** [geldata/gel-docker#97]
# Error Logs
```log
Bootstrapping Gel instance on the local volume...
/usr/local/bin/docker-entrypoint-funcs.sh: line 1221: -server-5: command not found
/usr/local/bin/docker-entrypoint-funcs.sh: line 1221: -server-5: command not found
/usr/local/bin/docker-entrypoint-funcs.sh: line 1221: -server-5: command not found
env: invalid option -- 's'
Try 'env --help' for more information.
ERROR: Could not complete instance bootstrap
```

# Docker Compose
```yaml
services:
  edgedb:
    image: edgedb/edgedb:5
    container_name: EdgeDB
    volumes:
      - "./data:/var/lib/edgedb/data"
    environment:
      EDGEDB_DOCKER_BOOTSTRAP_TIMEOUT_SEC: 500
      EDGEDB_SERVER_INSTANCE_NAME: EdgeDB
      EDGEDB_SERVER_ADMIN_UI: enabled
      GEL_SERVER_USER: <REDACTED>
      GEL_SERVER_PASSWORD: <REDACTED>
      GEL_SERVER_TLS_CERT_FILE: /traefik/fullchain.pem
      GEL_SERVER_TLS_KEY_FILE: /traefik/privkey.pem
    ports:
      - "5657:5656"
```
